### ISSUE TITLE
Subtotal Belum Ada

### ISSUE THREAD

**Issue by junifar** [junifar/erp-odoo-ext-web#1]
- Preventive

- Corrective

- Corrective/{Customer}/{Year}

- project

- project/{year}

- project/{year}/{project_type}

- project/{year}/{project_type}/{customer}

- budget_department

**Comment by sriaprianti98** [comment]
Preventive : Done

Corrective : Done

Corrective/{Customer}/{Year} : Done

project : Done

project/{year} : Done

project/{year}/{project_type} : Done

project/{year}/{project_type}/{customer} : Done

budget_department  : Done
